# Generated by Django 4.2 on 2023-09-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="price",
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
