# Generated by Django 4.2 on 2023-09-02 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0002_alter_crypto_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Crypto",
            new_name="Currency",
        ),
    ]
